use Mix.Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with brunch.io to recompile .js and .css sources.
#
# NOTE setup https locally from this
# http://ohanhi.com/phoenix-ssl-localhost.html
config :live_auction, LiveAuctionWeb.Endpoint,
  http: [port: 4000],
  https: [
    port: 4443,
    otp_app: :live_auction,
    keyfile: "priv/keys/localhost.key",
    certfile: "priv/keys/localhost.cert"
  ],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/.bin/webpack",
      "--watch",
      "--colors",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# command from your terminal:
#
#     openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com" -keyout priv/server.key -out priv/server.pem
#
# The `http:` config above can be replaced with:
#
#     https: [port: 4000, keyfile: "priv/server.key", certfile: "priv/server.pem"],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :live_auction, LiveAuctionWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$},
      ~r{priv/gettext/.*(po)$},
      ~r{lib/live_auction_web/views/.*(ex)$},
      ~r{lib/live_auction_web/templates/.*(eex)$}
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :live_auction, LiveAuction.Repo,
  adapter: Ecto.Adapters.Postgres,
  database: "live_auction_dev",
  hostname: "localhost",
  pool_size: 10

config :live_auction, LiveAuction.Auth.Guardian,
  secret_key: "TLzXhQ2+gSqRNaEMvuZrWwkfHiNkkcAARlrh4iavEYA/RrQ6A896FtrxnUxn5Qpp",
  ttl: {30, :days},
  verify_issuer: true

import_config "test.secret.exs"
