use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# ZaZaarWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :zazaar, ZaZaarWeb.Endpoint,
  load_from_system_env: true,
  http: [:inet6, port: "${PORT}"],
  https: [
    :inet6,
    port: "${SSL_PORT}",
    otp_app: :zazaar,
    keyfile: "priv/keys/private.key",
    certfile: "priv/keys/certificate.crt"
  ],
  force_ssl: [hsts: true],
  url: [host: "${HOSTNAME}", port: "${SSL_PORT}"],
  check_origin: false,
  server: true,
  root: ".",
  secret_key_base: "${SECRET_KEY_BASE}",
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure prod database
config :zazaar, ZaZaar.Repo,
  hostname: "${DB_HOST}",
  username: "${POSTGRES_USER}",
  password: "${POSTGRES_PASS}",
  database: "${POSTGRES_NAME}",
  adapter: Ecto.Adapters.Postgres,
  pool_size: 15

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: "237361706937885",
  client_secret: "f6f24c695581da27291b0cca18258530"

config :zazaar, OpenTok,
  key: "46185942",
  secret: "7e58a0e8bfc5fe6418a08a3c478bcdf8cc61399e"
# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :zazaar, ZaZaarWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [:inet6,
#               port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :zazaar, ZaZaarWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :zazaar, ZaZaarWeb.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"
